description: "Prepare repository and all dependencies"
name: "Install dependencies"

runs:
  steps:
    - name: Set up foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        run_install: false
        version: 8

    - name: Get pnpm store directory
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      shell: bash

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        path: ${{ env.STORE_PATH }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install
      shell: bash

  using: "composite"
